### ISSUE TITLE
Binaries in releases

### ISSUE THREAD

**Issue by willfurnell** [rivosinc/prometheus-slurm-exporter#86]
Hello,
Do you plan on distributing binaries with your releases? It would allow us to pull them directly from GitHub and not need to compile or build locally,
Thanks!

**Comment by willfurnell** [comment]
Oh actually - I suppose the binary would depend on SLURM versions as well wouldn't it as you use the SLURM libraries...

**Comment by abhinavDhulipala** [comment]
I do not use slurm libraries for the main exporter. I have an experimental module that interops with the c api and implements some of my `Fetcher` interfaces (not all), but that doesn't get built by default on go install. Putting deb and rpm releases has been a long term goal of mine, should be easy since this is statically linked. Just haven't gotten around to doing it yet. Open to contributions though. Otherwise, I'll get to it in the next couple of weeks.

**Comment by willfurnell** [comment]
I have created #92 which builds binaries :)

**Comment by abhinavDhulipala** [comment]
That's awesome @willfurnell. Thanks A ton. I'll take a look and give it a test drive.
