### ISSUE TITLE
Debian packaging for Slurm exporter

### ISSUE THREAD

**Issue by NucciTheBoss** [rivosinc/prometheus-slurm-exporter#96]
Greetings 👋

[I made a Debian package for this exporter](https://github.com/NucciTheBoss/prometheus-slurm-exporter/tree/deb-pkg/debian) and I wanted to contribute it back to the repository. I just had a couple questions before opening the PR:

1. Where would you like for me to place the Debian package recipe in the source tree? Currently I just have a top-level `debian/` directory since `build/` is taken by `just` for the built exporter binaries.

2. How necessary are the SWIG bindings for the exporter? The reason I ask is because they were causing the Debian package build to break as some of the data structures were undefined. I was able to fix the issue by removing `cmain.go` and `cext` from the source tree before executing `dpkg-buildpackage` and building the version that uses the Slurm CLI commands. I am using [`dh_golang`](https://go-team.pages.debian.net/packaging.html#_use_dh_golang) to compile the exporter for the Debian package. The tool seems to not like the presence of both `cmain.go` and `main.go` within the source tree. 

    Here's the errors that I was seeing when trying to build the exporter with `cmain.go` and `cext` still in the source tree:
    
    ```text
    github.com/rivosinc/prometheus-slurm-exporter/cext
    # github.com/rivosinc/prometheus-slurm-exporter/cext
    src/github.com/rivosinc/prometheus-slurm-exporter/cext/server.go:16:63: undefined: Destructor
    src/github.com/rivosinc/prometheus-slurm-exporter/cext/server.go:22:18: undefined: NewNodeFetcher
    src/github.com/rivosinc/prometheus-slurm-exporter/cext/server.go:25:17: undefined: NewJobFetcher
    src/github.com/rivosinc/prometheus-slurm-exporter/cext/server.go:29:31: undefined: Destructor
    dh_auto_build: error: cd obj-x86_64-linux-gnu && go install -trimpath -v -p 1 github.com/rivosinc/prometheus-slurm-exporter 
    github.com/rivosinc/prometheus-slurm-exporter/cext github.com/rivosinc/prometheus-slurm-exporter/exporter returned exit code 1
    make: *** [debian/rules:7: binary] Error 255
    dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
    debuild: fatal error at line 1184:
    dpkg-buildpackage -us -uc -ui --build=binary --build=binary failed
    ```

I'm also currently working on setting up a PPA in Launchpad for hosting public builds of the exporter for Ubuntu. Hope to chat soon!

**Comment by drewstinnett** [comment]
I've had a fair amount of success building an publishing debian packages with [goreleaser](https://goreleaser.com/), like in the PR above. It uses [nfpm](https://nfpm.goreleaser.com/) under the covers...pretty basic but has been able to do most of what I've needed. The nice thing about using GoReleaser, in addition to it already building the binaries here, is that it can publish right to GitHub or other spots at publish time, without needing to run another tool. I'd be happy to help set those pieces up as well!

**Comment by abhinavDhulipala** [comment]
Howdy! Firstly, thanks a ton for your contributions here. To answer your questions:

1. a top level debian directory is a perfect place to put these
2. The `cext` is a experimental pkg for using the c api headers to dynamically link against a locally installed slurm so we can use the c api instead of the cli or json implementation which change, sometimes without warning. Please **do not** package the c api. If you look at our existing goreleaser implementation, we do not build this module in at all and only call `main.go`. In fact, if you use the go cli to build the binary, it also doesn't build the cext so conceivably you could simply `go install github.com/rivosinc/prometheus-slurm-exporter@<some.tag>`, copy the binary, then pkg the html templates in `./exporter/templates/*` (just like our archive already does) and release the package. Optionally, if you are installing it as a debian pkg, you can shim in the template directory using `TRACE_ROOT_PATH` env var as introduced by PR #95. As far as the specifics of the packaging tool goes, I see that it is supposed to just run `go install ...`. Not sure why it pulls cmain.go or cext at all? You can validate this with a clean docker container by doing the following:

```bash
$ docker run -ti --rm golang bash
root@352e8d3a41c6:/go# go install github.com/rivosinc/prometheus-slurm-exporter@latest
go: downloading github.com/rivosinc/prometheus-slurm-exporter v1.6.4
go: downloading golang.org/x/exp v0.0.0-20230905200255-921286631fa9
go: downloading github.com/prometheus/client_golang v1.16.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/common v0.42.0
go: downloading github.com/prometheus/procfs v0.10.1
go: downloading google.golang.org/protobuf v1.30.0
go: downloading github.com/golang/protobuf v1.5.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading golang.org/x/sys v0.12.0
```

and noticing how no cext or swig is compiled.
