### ISSUE TITLE
[bug] squeue runs do not respect slurm.poll-limit

### ISSUE THREAD

**Issue by drewstinnett** [rivosinc/prometheus-slurm-exporter#98]
It looks like when the exporter runs the `squeue` command, it is run every time the metrics are queried, regardless of if it's withing the poll-limit timing. This is what I'm seeing:

```bash
$ LOGLEVEL=debug prometheus-slurm-exporter -slurm.poll-limit=300
time=2024-08-29T11:38:35.312-04:00 level=INFO msg="serving metrics at :9092/metrics"
## I ran a curl against the URL and see both commands as expected
time=2024-08-29T11:38:39.918-04:00 level=DEBUG msg="cmd squeue --states=all -h -r -o {\"a\": \"%a\", \"id\": %A, \"end_time\": \"%e\", \"u\": \"%u\", \"state\": \"%T\", \"p\": \"%P\", \"cpu\": %C, \"me
m\": \"%m\", \"array_id\": \"%K\"} took 4.678179ms secs"
time=2024-08-29T11:38:39.938-04:00 level=DEBUG msg="cmd sinfo -h -o {\"s\": \"%T\", \"mem\": %m, \"n\": \"%n\", \"l\": \"%O\", \"p\": \"%R\", \"fmem\": \"%e\", \"cstate\": \"%C\", \"w\": %w} took 25.09
0378ms secs"
## here I ran the curl command, expecting to not see any commands run since we are still within the 300 seconds
time=2024-08-29T11:39:26.063-04:00 level=DEBUG msg="cmd squeue --states=all -h -r -o {\"a\": \"%a\", \"id\": %A, \"end_time\": \"%e\", \"u\": \"%u\", \"state\": \"%T\", \"p\": \"%P\", \"cpu\": %C, \"me
m\": \"%m\", \"array_id\": \"%K\"} took 5.523552ms secs"
```
I should the queue command have been cached as well? If so, I think that piece is busted...I tried digging in to see if I could figure out myself but couldn't get very far...happy to dig in more if you have any pointers on where to look!

Thank you!

**Comment by abhinavDhulipala** [comment]
sorry yeah, that's a stupid bug. I noticed that too. The problem is [here](https://github.com/rivosinc/prometheus-slurm-exporter/blob/main/exporter/jobs.go#L58-L65). I'll push a fix on that today. I put the caching feature after the basic squeue commands and didn't protect the actual scraping of of the cli.

**Comment by abhinavDhulipala** [comment]
sorry yeah, that's a stupid bug. I noticed that too. The problem is [here](https://github.com/rivosinc/prometheus-slurm-exporter/blob/main/exporter/jobs.go#L58-L65). I'll push a fix on that today. I put the caching feature after the basic squeue commands and didn't protect the actual scraping of of the cli. The code should be something like:

```go
func (jjf *JobJsonFetcher) FetchMetrics() ([]JobMetric, error) {
	return jjf.cache.FetchOrThrottle(func() ([]JobMetric, error) {
		data, err := jjf.scraper.FetchRawBytes()
		if err != nil {
			jjf.errCounter.Inc()
			return nil, err
		}
		return parseJobMetrics(data)
	})
}

```
Thanks again for noticing 👍
